### ISSUE TITLE
Cocoapods (and Carthage?) support

### ISSUE THREAD

**Issue by mattmaddux** [Yubico/yubikit-ios#10]
I'm currently trying to build my own private Cocoapods wrapper for Yubikit. It would be really nice if Cocoapods were supported by the repo itself. I didn't have any problem integrating the library manually, but I like to keep my dependencies a little cleaner than that, and Cocoapods would go a long way to help with that.

**Comment by imakhalova** [comment]
Hey @mattmaddux, thank you for your request. 
For now you can add this to your pod file:
  pod 'YubiKit', :git => 'https://github.com/Yubico/yubikit-ios.git'
We will publish our next release version to CocoaPods trunk and you'll be able to switch to version number.

**Comment by mattmaddux** [comment]
Oh, how did I not see the Podspec file! Great! That works just as well.
