### ISSUE TITLE
YubiKitDemo Build Failure - library not found for -lYubiKit

### ISSUE THREAD

**Issue by Dsanchez0121** [Yubico/yubikit-ios#102]
Hello,
I cloned the YubiKitDemo and tried to build it. I got this error when building "ld: library not found for -lYubiKit
clang: error: linker command failed with exit code 1 (use -v to see invocation)" Am I missing a step?

**Comment by Dsanchez0121** [comment]
Potentially fixed it: added YubiKit as a package dependency. File -> Add Packages -> type in https://github.com/Yubico/yubikit-ios in top right corner -> Add Package

**Comment by WWSellers** [comment]
That happened to me when I tried to build it from yubikit-ios/YubiKitDemo/YubiKitDemo.xcodeproj.   
Building from yubikit-ios/YubiKit.xcworkspace with scheme "YubiKitDemo" chosen worked for me. (With iphone device chosen rather than a simulator.)

**Comment by jensutbult** [comment]
Yes, you need to open the Yubikit SDK workspace and build the demo from there.
