### ISSUE TITLE
Several 'not in scope errors'

### ISSUE THREAD

**Issue by Dsanchez0121** [Yubico/yubikit-ios#103]
Encountered these errors in YubiKitDemo/YubiKitDemo/Demos/FIDO2/FIDO2ViewController:
Cannot find 'YubiKitManager' in scope
Cannot find 'YubiKitDeviceCapabilities' in scope
Cannot find 'YubiKitManager' in scope

Am I missing something here?

**Comment by WWSellers** [comment]
Is it being built from YubiKit.xcworkspace with "YubiKitDemo" scheme selected?

**Comment by jensutbult** [comment]
I'm assuming this is caused by not building the demo from the workspace. If not please reopen the issue.
