### ISSUE TITLE
NFC implementation documentation missing Info.plist key

### ISSUE THREAD

**Issue by rudyrichter** [Yubico/yubikit-ios#11]
The key for the AIDs seems to be missing from the copy/paste (Xcode doesn't include the key when copying a sub-section of an Info.plist). I believe it should have a:

`<key>com.apple.developer.nfc.readersession.iso7816.select-identifiers</key>` with the array on https://github.com/Yubico/yubikit-ios/blame/master/NFC-Notes.md#L30

**Comment by imakhalova** [comment]
Thank you, you're right, we'll fix it.

**Comment by imakhalova** [comment]
Documentation was updated with this commit https://github.com/Yubico/yubikit-ios/commit/5ce9487c01bad89be46f3c54caca2d4727524a50.
