### ISSUE TITLE
Library Not found when running YubiKitDemo

### ISSUE THREAD

**Issue by mmoraga** [Yubico/yubikit-ios#121]
Trying to run the YubiKitDemo in XCode14 using the README instructions gives this error:

```
error build: Library not found for -lYubiKit
```

I tried removing the library references and adding Yubikit manually using SPM but that gave me a bunch of different errors.

**Comment by WWSellers** [comment]
That happened to me when I tried to build it from yubikit-ios/YubiKitDemo/YubiKitDemo.xcodeproj.
Building from yubikit-ios/YubiKit.xcworkspace with scheme "YubiKitDemo" chosen with iOS device worked for me.
