### ISSUE TITLE
YubiKitDeviceCapabilities.supportsMFIAccessoryKey incorrect on iPad Pro 6th Gen

### ISSUE THREAD

**Issue by jbickerton** [Yubico/yubikit-ios#126]
YubiKitDeviceCapabilities.supportsMFIAccessoryKey is returning true for latest iPad device, when the device does not provide support for this (has USB-C not lightning).

**Comment by WWSellers** [comment]
What is the model ID of your iPad?  (example:  iPad8,1)
Maybe the list in this method needs to be updated.
+[YubiKitDeviceCapabilities supportsMFIAccessoryKey]
https://github.com/Yubico/yubikit-ios/blob/main/YubiKit/YubiKit/YubiKitDeviceCapabilities.m

**Comment by WWSellers** [comment]
Does this mean you are seeing issues when your app tries to call startAccessoryConnection()?

**Comment by jensutbult** [comment]
FYI both `startAccessoryConnection()` and `startSmartCardConnection()` are safe to be called even if the device doesn't support them. `startAccessoryConnection()` will hit an Assert in debug builds on unsupported devices though but not in production.
