### ISSUE TITLE
iPhone 15 Pro

### ISSUE THREAD

**Issue by joeblau** [Yubico/yubikit-ios#135]
I plugged my 5C into my iPhone 15 Pro's USB-C port then ran a sample project and this command returns `false`.

`YubiKitDeviceCapabilities.supportsSmartCardOverUSB`

Sample iOS project: https://github.com/joeblau/yubi3
Code that fails: https://github.com/joeblau/yubi3/blob/main/Yubi3/SmartCard.swift#L16-L27

<img width="797" alt="Screenshot 2023-09-23 at 7 21 40 PM" src="https://github.com/Yubico/yubikit-ios/assets/1218847/f3670a31-da31-458d-a22e-b128d00b25ee">

**Comment by WWSellers** [comment]
The code for `supportsSmartCardOverUSBC` (YubiKitDeviceCapabilities.m:127) maintains a table of known devices with USB-C, which has not yet been updated yet.

Device model strings are mapped to yubikit constants in ykf_setupDeviceModel (UIDeviceAdditions.m:22). 

For a short-term patch to allow testing on your devices, you might want to add your device to the code. 

To help with updating the tables, I suggest posting your iPhone's model ID string to this issue. (Example: iPhone14,7).

**Comment by joeblau** [comment]
Thanks @WWSellers!

I submitted a PR with the fixes: https://github.com/Yubico/yubikit-ios/pull/136
