### ISSUE TITLE
Do you have plans to support macOS

### ISSUE THREAD

**Issue by izouxv** [Yubico/yubikit-ios#150]
Hi

Do you have plans to support macOS , a object-c or swift macOS sdk
Thank you

**Comment by jensutbult** [comment]
There will be no support for macOS in this SDK. However, the new Swift SDK supports macOS using the TKSmartCard API. It currently supports the PIV, OATH and Management application. Support for more applications will be added in the future. The Swift SDK is currently in pre-release and can be found here: https://github.com/Yubico/yubikit-swift.
