### ISSUE TITLE
YKFDeviceModel missing newer devices

### ISSUE THREAD

**Issue by rudyrichter** [Yubico/yubikit-ios#16]
the iPhone 11 series seem to be missing from the list on https://github.com/Yubico/yubikit-ios/blob/master/YubiKit/YubiKit/Helpers/Additions/UIDeviceAdditions.h

**Comment by imakhalova** [comment]
Thank you for pointing that, we might add them.
FYI this is not required for SDK, because it assumes that all unknown models (new iPhones) have support of NFC. This list is only to be able detect unsupported models (the ones that don't have NFC or Lightning port).

**Comment by rudyrichter** [comment]
Fixed by #18
