### ISSUE TITLE
PGP Support

### ISSUE THREAD

**Issue by repomaa** [Yubico/yubikit-ios#19]
I didn't see any examples for smart card features here at least. Afaik this is possible on android.

**Comment by imakhalova** [comment]
`rawCommandService` allows you to use all smart card features. You would need SDK to get this service and then use the same logic as you would use on Android: send APDU commands to select PGP applet and execute commands

**Comment by imakhalova** [comment]
FYI: PGP implementation on YubiKey follows this documentation: https://gnupg.org/ftp/specs/OpenPGP-smart-card-application-2.0.pdf
If you could share what scenario you're trying to cover it could help us to provide better guidance or architect high level API.

**Comment by Erik1000** [comment]
So is it possible to interact with the PGP Smart card only over lighting / usb c on the iPad airs and pros or is NFC supported too? On Android it is possible but I've heard that Apple has quite limited the possibilities for NFC communication. If it is not possible, maybe Yubico could get in touch with Apple or something.

**Comment by jensutbult** [comment]
No NFC support on any iPads so lightning is the only way. USB-C is not supported since apple has decided not to open up any APIs for that port. Apple is aware of the situation but if you want you can file a radar which might get more attention on the issue.
