### ISSUE TITLE
TOTP Support

### ISSUE THREAD

**Issue by chrenderle** [Yubico/yubikit-ios#24]
Am I understanding it correctly that I can currently only read the Yubikey OTPs but not TOTPs with the SDK except with the raw commands? By TOTPs I mean the ones I can use with the Yubikey Authenticator App.

If this is the case I would like to see this feature in the future.

**Comment by imakhalova** [comment]
You can generate/calculate TOTPs on YubiKey using OATH applet (https://github.com/Yubico/yubikit-ios/blob/master/docs/oath.md). 
Just FYI there is Authenticator app in Apple store that Yubico maintains. In case if you were looking for ready-to-use solution.
