### ISSUE TITLE
HMAC-SHA1 Challenge-Response mode

### ISSUE THREAD

**Issue by keepassium** [Yubico/yubikit-ios#3]
YubiKit 2.0.0 supports several modes, but the challenge-response one is not listed (although it is mentioned in the [YubiKey 5 Series Technical Manual](https://support.yubico.com/support/solutions/articles/15000014219-yubikey-5-series-technical-manual#HMAC-SHA1_Challenge-Responsef4peio)).

Understandably, there used to be a technical limitation on two-way communication between the key and iOS device. However, now we have Yubikey 5Ci and extended NFC support in iOS 13.

The challenge-response mode is used by offline password managers, in particular KeePass / KeePassXC ([details](https://keepassxc.org/docs/#faq-yubikey-2fa)). I would love to add Yubikey support to my iOS port of KeePass, too — this is one of the [most requested features](https://github.com/keepassium/KeePassium/issues/25). 

So, how can we use the challenge-response mode with YubiKit 2.0?

**Comment by JaredPotter** [comment]
As a regular Yubikey NFC user I would highly appreciate this support being added to the iOS SDK.

**Comment by imakhalova** [comment]
Thank you @keepassium for your feature request. 
Currently you can implement it within your app using raw command service to communicate with 5ci YubiKey. We will appreciate your efforts and  feedback on usage of SDK.

This feature is not in top of our priorities list yet. But we'll reevaluate it later this year.

**Comment by keepassium** [comment]
@imakhalova , thank you for the response. 

As I understood, that the raw command service solution:

1. is currently limited to 5Ci only
2. won't work over NFC any time soon (even with the new NFC capabilities in iOS 13)

Can you please confirm these?

**Comment by mmcguill** [comment]
Hi @imakhalova - I'm also keen to use Yubikey in my iOS Password Manager ([Strongbox](https://apps.apple.com/us/app/strongbox-password-safe/id897283731)), it is one of the most frequently requested features.

Would you have any kind of ballpark timeline I can give my users for implementation of NFC Challenge Response support?

**Comment by imakhalova** [comment]
Thank you for your request @mmcguill . Currently I can't give you dates on that specific feature, but what I can provide is: some preview version of raw commands NFC communication with YubiKey in November. And challenge-response implementation should be just sending couple APDUs (select applet and send challenge)...

**Comment by mmcguill** [comment]
Thanks for the response @imakhalova - While it's less than ideal, would prefer a high level API to work across different Yubikeys, I look forward to seeing that. Cheers!

**Comment by markshiz** [comment]
@imakhalova I am also interested in HMAC/SHA1 Challenge Response and am perfectly comfortable using `YKFAPDU` to do so.   However, I don't see any documentation around what the supported RAW commands are.  I have joined the developer program above, but also can't find any information there either.

Are the supported RAW commands documented somewhere?  For the moment I am specifically interested in writing the secret key for an HMAC/SHA1 Challenge Response and validating a response.

**Comment by imakhalova** [comment]
Hey @markshiz , thank you for you interest. I have to agree with you that currently we lack of documentation regarding of custom commands (not PIV or FIDO/U2F standards) that YubiKey can support. 
Here is quick help on HMAC/SHA1 challenge response:
AID: 0xA0, 0x00, 0x00, 0x05, 0x27, 0x20, 0x01, 0x01 (so full APDU command shall be  00 A4 04 00 08 A0 00 00 05 27 20 01 01)
And APDU for sending challenge cla:0 ins:0x01 p1:0x30 p2:0 + the size and challenge byte array
p1 corresponds to slot (0x30 - 1 slot, 0x38 - 2 slot)

As for setting secret key currently I would suggest to refer to YubiKey personalization tool or YubiKey Manager. But I added task to prepare sample for this to backlog.

**Comment by markshiz** [comment]
@imakhalova I will also add these resources to share with others that I found through looking at this Github project: https://github.com/pp3345/ykDroid

These actually did help me somewhat.
- https://developers.yubico.com/OATH/YKOATH_Protocol.html
- https://webstore.ansi.org/preview-pages/ISO/preview_ISO+IEC+7816-4-2013.pdf

Though revisiting this reminds me: is there no way to programmatically set the secret key via raw command outside of the YubiKey Manager?

**Comment by imakhalova** [comment]
Hey @markshiz, thank you for sharing resources. Yes, the first link is actual implementation APDUs for challenge-response.
Not sure how YKOATH will help you though, because it's different "applet" on YubiKey and can be used only for OATH TOTPs/HOTPs.

Of cause there is a way to programmatically set the secret key, that's how YubiKey Manager does it, so that means everyone can do it.
What I meant is that I don't have it well-documented explaining the APDU command structure for that operation, but [ykpers](https://github.com/Yubico/yubikey-personalization) is open source and you can take a look at implementation or debug what APDU commands its sending when sets the secret key.
Feel free to share your findings here, may be it will help someone else.

**Comment by imakhalova** [comment]
Addressed with https://github.com/Yubico/yubikit-ios/pull/23
