### ISSUE TITLE
YKFKeyCommandConfiguration.h missing from Copy Files Build Phase

### ISSUE THREAD

**Issue by mtamburro** [Yubico/yubikit-ios#37]
FYI, you'll need to add this header so it gets exported.

Also: can you please version the SDK with each commit, and provide a change log?  Thanks!

**Comment by imakhalova** [comment]
Hello @mtamburro ,
Thank you so much for your feedback. 
Let me add missing file.
I don't think that we plan to release SDK with every commit. But I agree that this SDK didn't have release for a while. So let me prepare it with changelog sometime next week.

**Comment by imakhalova** [comment]
Addressed in https://github.com/Yubico/yubikit-ios/pull/38
