### ISSUE TITLE
TLS client certificate through PIV over NFC

### ISSUE THREAD

**Issue by oddbjornkvalsund** [Yubico/yubikit-ios#5]
I'm currently analyzing the possibilities of using Yubikeys for TLS client certificate authentication over NFC on iOS devices as part of a single sign-on process, but from what I have been able to gather only OTP seems to been supported? Are there any plans for supporting PIV over NFC?

**Comment by imakhalova** [comment]
Thank you for your feature request.

Apple expanded API for NFC with ability 2-way communication only in iOS 13 (which is not officially released yet, but coming).

So I would suggest you to start implementing your PIV client over lightning port using [raw command service](https://github.com/Yubico/yubikit-ios#integration_steps_3_5). And then expand it to NFC later on.

**Comment by oddbjornkvalsund** [comment]
Okay, thanks! Would you be able to supply example code showing how a private key + certificate stored on the Yubikey 5Ci could be integrated with a `WKWebView` for strong TLS client authentication over Lightning? Is this a scenario you support?

**Comment by imakhalova** [comment]
Theoretically you can implement that with YubiKey and existing SDK. 
[RawCommandServiceDemoViewController](https://github.com/Yubico/yubikit-ios/blob/master/YubiKitDemo/YubiKitDemo/UI/Other/Demos/RawCommandServiceDemoViewController.swift) will give you a good start on that.
You can also check existing desktop [piv tool](https://github.com/Yubico/yubico-piv-tool) for full set of PIV functionality supported within YubiKey.

**Comment by jensutbult** [comment]
PIV support has been added to the SDK now so we're closing this issue.

**Comment by luky88** [comment]
Hi @jensutbult, is there any possibility to receive an answer to this question?

> Can you please tell me how did you construct URLCredential for the WKWebView through PIV card on iOS?

Reading the docs and using the SDK it seems to be possible to obtain only a SecCertificate from a PIV session, but to use a TLS client authentication within a WKWebView a SecIdentity is needed.

An help will be really appreciated! 
Thanks in advance
