### ISSUE TITLE
Cocoapods for release 3.2.0 aren't working.

### ISSUE THREAD

**Issue by LamarLugli** [Yubico/yubikit-ios#58]
Can you please look into releasing a cocoapod update for release 3.2.0?  The latest cocoapod release is 3.1.0.

In my app, if I try to specify it using the specific github url and branch name in PodFile, it dumps a ton of text to the screen and shows:

[!] [Xcodeproj] Generated duplicate UUIDs:

Thanks

**Comment by jensutbult** [comment]
This should be fixed in the 4.0 release.
