### ISSUE TITLE
Can't sign data using RSA 2048 key in slot 9a using YKFSCardTransmit over Lightning

### ISSUE THREAD

**Issue by MichaelBuckley** [Yubico/yubikit-ios#6]
Hello,

I'm attempting to implement PKCS#11 support on iOS using the PCSC-like interface in YubiKit on iOS, and PCSC.framework on Mac over USB-C. The code is inspired by the PKCS#11 implementation in yubico-piv-tool, and works on Mac.

On iOS, most of the code is working. I'm using `YKFSCardConnect`, `YKFSCardReconnect`, `YKFSCardDisconnect`, `YKFSCardStatus`, `YKFSCardListReaders` without issue, and in most cases, `YKFSCardTransmit` is working properly. However, when I go to sign data using an RSA 2048 key stored in slot 9a, instead of prompting the user to tap the device, the Yubikey 5ci returns `0x6982`, authentication fired.

My iOS app contains `com.yubico.ylp` as a supported external accessory protocol in the app's Info.plist. My code ends up calling `YKFSCardTransmit` twice, and I've pasted the data sent below (with `XX` being the data to sign). I confirmed the code sends the same data on macOS to `SCardTransmit`. On the Mac, on the second call to `SCardTransmit`, the function blocks until the user taps the device.

```10 87 07 9A FF 7C 82 01 06 82 00 81 82 01 00 XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX```

```00 87 07 9A 0B XX XX XX XX XX XX XX XX XX XX```

I understand this is a complicated use-case. Please let me know if I can provide any additional info.

**Comment by MichaelBuckley** [comment]
Hoping that it might be useful, I implemented yubico-piv-tool-style verbose logging and logged all the bytes read and written to the device. I'll attach the logs and the diff here. I removed responses from the logs that might contain sensitive information, and I replaced the PIN and data to be encrypted with XX.

I made sure to diff the logs before I removed the responses, to ensure I was getting the same data off the device each time.

In the diff, you can see that the only differences between the two logs is the reported name of the reader (`Yubico Yubikey 4 OTP+U2F+CCID` on Mac, `Yubikey` on iOS) and the result of the signing operation at the end. The signing operation succeeds on Mac, but fails on iOS.

Since the bytes sent are identical, is it possible the device's hardware just doesn't support this operation over the lighting connector?

[yubi-mac.txt](https://github.com/Yubico/yubikit-ios/files/3611076/yubi-mac.txt)
[yubi-ios.txt](https://github.com/Yubico/yubikit-ios/files/3611078/yubi-ios.txt)
[diff.txt](https://github.com/Yubico/yubikit-ios/files/3611080/diff.txt)

**Comment by imakhalova** [comment]
Thank you for reporting the issue.
Can you also please share the firmware version of your YubiKey please?
One of the ways to check it: [YubiKey manager](https://www.yubico.com/products/services-software/download/yubikey-manager/))?

**Comment by MichaelBuckley** [comment]
Thanks for the response! The Yubikey manager reports:

Yubikey 5Ci
Firmware: 5.2.3

**Comment by imakhalova** [comment]
I'm sorry that you've got this issue. 
I was able to reproduce issue when I don't touch a key and it times out with SW 0x6982. Then next attempts to sign failed with this error without waiting for touch. 
Short-term "workaround" to unplug the key and plug it again.

Can you please contact [yubi.co/support](yubi.co/support) to open a case for you? Please refer to this github issue.

**Comment by MichaelBuckley** [comment]
Thank you. I will file an issue there after doing a little more research. I apologize for filing it here first. I originally though that this was an issue with the YubiKit library, since even unplugging and plugging it in again didn't work for me, but I was able to get it to work on a different Yubikey.
