### ISSUE TITLE
macOS usage?

### ISSUE THREAD

**Issue by Fonta1n3** [Yubico/yubikit-ios#68]
Ive got this library working great in a Mac catalyst project, however it only seems to work on iPhone and not on a Mac. Any idea why that may be?

**Comment by dmennis** [comment]
@Fonta1n3 This is a good question. As developers, we all hope the "catalyst" checkbox will makes all our mobile apps and libraries just work on desktop (MacOS). That is true in some cases but the reality always depends on the type of app and what resources are being accessed. The YubiKit for iOS was intended and development is primarily focused on supporting the mobile devices with specific functionality and connections like NFC and Lightning connector to name a few.  

This library has not been tested to interact with YubiKeys on MacOS, however, this shouldn't block you from trying. Could you tell us what YubiKey features and protocols your app will be using on MacOS? Also, do any parts of your MacOS catalyst app work?

**Comment by jensutbult** [comment]
As you already figured out the iOS SDK only supports communicating with the YubiKey using the External Accessory Framework and NFC. Since neither of these are available on MacOS the SDK will not be able to establish a connection to a YubiKey on MacOS. You're also right about the desktop authenticator app being a QT app.

**Comment by robb-j** [comment]
Hey, with the new `CryptoTokenKit` library on iPadOS and macOS, could macOS support be revisited?

**Comment by robb-j** [comment]
Hey, I ended up making my own implementations for LIST and CALCULATE for a Mac app, based on CryptoKit if you’re interested to see what it looks like. https://github.com/robb-j/MiniYubiOath/blob/main/MiniYubiOath/OathStore/SmartCardOathStore.swift
