### ISSUE TITLE
Not receiving Pin Verification

### ISSUE THREAD

**Issue by Brandon-T** [Yubico/yubikit-ios#7]
When attempting to use security key with pin with login.live.com, I do not receive a `YKFKeyFIDO2ErrorCodePIN_REQUIRED`.

Steps:
- Create a login.live.com account.
- Register a YubiKey with it with a PIN.
- Log out.
- Attempt to sign in with the key.
- Receives an error on the website but nothing in the SDK.

Expected:
- Should receive `YKFKeyFIDO2ErrorCodePIN_REQUIRED`

**Comment by imakhalova** [comment]
Thank you for reporting. Looking into that.

**Comment by imakhalova** [comment]
This seems like related to this issue: https://github.com/brave/brave-ios/issues/1584
Closing this issue as it doesn't need to be addressed in SDK (at least at this point).  
And it seems like investigation is covered by our solution engineers and via different channels. 

Also referencing this as it might be related:
Reference: https://groups.google.com/a/fidoalliance.org/forum/?utm_medium=email&utm_source=footer#!msg/fido-dev/yHTj3vIbv_c/wArhV2liAAAJ
