### ISSUE TITLE
API endpoint

### ISSUE THREAD

**Issue by Fonta1n3** [Yubico/yubikit-ios#70]
Is this the correct endpoint we should be using in production for registration?

`"https://demo.yubico.com/api/v1/user/%@/webauthn/register-begin"`

I am getting an issue where my registered credentials (via that endpoint) are no longer recognized as valid after around 24 hours...

**Comment by dmennis** [comment]
That URL is only for testing the FIDO2 feature of the YubiKit for iOS and credentials are cleared at least every 24hrs by design.  Once you have successfully tested the WebAuthn ceremony in your app, you'll want to build and/or connect to your own WebAuthn server.

**Comment by Fonta1n3** [comment]
Thanks that makes sense.

Do you have any recommended guide for setting one up on linux?

**Comment by jensutbult** [comment]
https://github.com/Yubico/java-webauthn-server contains some useful instructions on how the set it up.
