### ISSUE TITLE
[Question] Using NFC only option without MFi review

### ISSUE THREAD

**Issue by Emailsbi** [Yubico/yubikit-ios#82]
Hello,
Sorry if I missed it somewhere, but I couldn't really get a clear understanding whether is it possible to use this SDK for WebAuthn assertion with NFC only and not doing all that MFi-related review process. 
And as a follow-up question: would YubiKey 5Ci work in NFC mode in this case?

Thank you

**Comment by dmennis** [comment]
Hi, Emailsbi.

Yes, this SDK can be used for WebAuthn assertion over NFC only and does not require MFi approval. However, your app will not support the YubiKey 5Ci when connected to the Lightning connector unless you have MFi approval. If you are only supporting NFC, make sure you don't have the custom protocol (com.yubico.ylp) in your Info.plist or the App Store reviewers will assume you are trying to communicate with the YubiKey 5Ci over the Lightning connector.

As for the MFi review process,  the approval only requires that you submit a form to Yubico developer program and share the functionality your app has with the YubiKey 5Ci. The review and approval takes just a couple days. 

The YubiKey 5Ci does not have NFC capabilities.

**Comment by Emailsbi** [comment]
@dmennis Thank you very much
